apiVersion: v1
kind: Service
metadata:
  labels:
    app: events-api-svc
  name: events-api-svc
  namespace: default
spec:
  selector:
    app: events-api
    ver: v1.0
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-api
  labels:
    app: events-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-api
      ver: v1.0
  template:
    metadata:
      labels:
        app: events-api
        ver: v1.0
    spec:
      containers:
      - image: imcbeth/events-api:v1.0
        name: events-api
        env:
        - name: DBHOST
          value: "my-mariadb"
        - name: DBUSER
          value: "root"
        - name: DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: my-mariadb
              key: mariadb-root-password
        - name: DBDATABASE
          value: "events_db" 
        ports:
        - containerPort: 8082
      imagePullSecrets:
      - name: docker-registry-secret