apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: | 
    ewoJImF1dGhzIjogewoJCSJkb2NrZXIucGtnLmdpdGh1Yi5jb20iOiB7CgkJCSJhdXRoIjogIlZW
    TkZVazVCVFVVNloyaDFYMjlVYkhCNmVXaEpZWEIxWkVGVVlWWk5jRkpCVld0TGNtVk1aVzFyYURC
    c1kxUkVZUT09IgoJCX0sCgkJImdoY3IuaW8iOiB7CgkJCSJhdXRoIjogImFXMWpZbVYwYURwbmFI
    VmZiMVJzY0hwNWFFbGhjSFZrUVZSaFZrMXdVa0ZWYTB0eVpVeGxiV3RvTUd4alZFUmgiCgkJfSwK
    CQkiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjogewoJCQkiYXV0aCI6ICJhVzFqWW1WMGFE
    cDZTMkV5VEZsak5YaFJkV3c9IgoJCX0KCX0sCgkiSHR0cEhlYWRlcnMiOiB7CgkJIlgtTWV0YS1T
    b3VyY2UtQ2xpZW50IjogImdpdGh1Yi9jb2Rlc3BhY2VzIgoJfQp9