apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-website
  labels:
    app: events-website
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-website
      ver: v3.0
  template:
    metadata:
      labels:
        app: events-website
        ver: v3.0
    spec:
      containers:
      - image: imcbeth/events-website:v3.0
        name: events-site
        ports:
        - containerPort: 8082
      imagePullSecrets:
      - name: docker-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: events-web-svc
  name: events-web-svc
  namespace: default
spec:
  selector:
    app: events-website
    ver: v3.0
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer